name: My Action
description: This is a test
inputs:
  project:
    description: Path to stuff we want to have access to inside this container
    required: true
  release:
    description: '--release'
    required: true
    default: true
  debug:
    description: '--debug'
    required: true
    default: false
outputs:
  location:
    description: Path to stuff this action has touched
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.project }} ${{ inputs.release }} ${{ inputs.debug }}
