name: CI

on:
  push:
  workflow_dispatch:
    inputs:
      release:
        description: '--release'
        required: true
        default: true
      debug:
        description: '--debug'
        required: true
        default: false

jobs:
  do-the-thing:
    name: Do the Thing
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run action
        uses: ./.github/actions/my-action
        id: my-action
        with:
          project: local
          release: ${{ inputs.release }}
          debug: ${{ inputs.debug }}
      - run: echo ${{ steps.my-action.outputs.location }}
